// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN212_VietnameseEduChat.DataAccess.Context;

#nullable disable

namespace PRN212_VietnameseEduChat.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713162042_ExpandPaymentForPayOS")]
    partial class ExpandPaymentForPayOS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMessageId"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatMessageSource", b =>
                {
                    b.Property<int>("ChatMessageSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMessageSourceId"));

                    b.Property<int>("ChatMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentChunkId")
                        .HasColumnType("int");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("float");

                    b.HasKey("ChatMessageSourceId");

                    b.HasIndex("ChatMessageId");

                    b.HasIndex("DocumentChunkId");

                    b.ToTable("ChatMessageSources");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatSession", b =>
                {
                    b.Property<int>("ChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatSessionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChunkingConfiguration", b =>
                {
                    b.Property<int>("ChunkingConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChunkingConfigurationId"));

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FixedSizeUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StrategyKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ChunkingConfigurationId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("ChunkingConfigurations");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("DocumentChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentChunkId"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.HasKey("DocumentChunkId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<bool>("AllowAiFeatures")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DailyQuestionLimit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxDocuments")
                        .HasColumnType("int");

                    b.Property<int>("MaxUploadSizeMb")
                        .HasColumnType("int");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PackageId");

                    b.HasIndex("PackageCode")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankBin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("PackageCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PackageDurationDaysSnapshot")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PackageNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PackagePriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProviderPaymentLinkId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SourceSubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("TargetEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TransferDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasFilter("[OrderCode] IS NOT NULL");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProviderPaymentLinkId")
                        .IsUnique()
                        .HasFilter("[ProviderPaymentLinkId] IS NOT NULL");

                    b.HasIndex("ProviderReference")
                        .IsUnique()
                        .HasFilter("[ProviderReference] IS NOT NULL");

                    b.HasIndex("SourceSubscriptionId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchDocumentChunk", b =>
                {
                    b.Property<int>("ResearchDocumentChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchDocumentChunkId"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<string>("ChunkingStrategyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChunkingStrategyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ResearchDocumentChunkId");

                    b.HasIndex("DocumentId", "ChunkingStrategyKey", "EmbeddingModelName", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("ResearchDocumentChunks");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchExperiment", b =>
                {
                    b.Property<int>("ResearchExperimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchExperimentId"));

                    b.Property<string>("AnswerModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<string>("ChunkingStrategyKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("fixed-baseline");

                    b.Property<string>("ChunkingStrategyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("OpenAI");

                    b.Property<string>("ExperimentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExperimentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TopK")
                        .HasColumnType("int");

                    b.HasKey("ResearchExperimentId");

                    b.ToTable("ResearchExperiments");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchQuestion", b =>
                {
                    b.Property<int>("ResearchQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchQuestionId"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroundTruthAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ResearchQuestionId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ResearchQuestions");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchResult", b =>
                {
                    b.Property<int>("ResearchResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchResultId"));

                    b.Property<double>("AnswerSimilarityScore")
                        .HasColumnType("float");

                    b.Property<double>("ContextRelevanceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratedAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GroundednessScore")
                        .HasColumnType("float");

                    b.Property<double>("KeywordHitScore")
                        .HasColumnType("float");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<int>("ResearchExperimentId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("RetrievedContext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetrievedSourcesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResearchResultId");

                    b.HasIndex("ResearchExperimentId");

                    b.HasIndex("ResearchQuestionId");

                    b.ToTable("ResearchResults");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.SubjectLecturer", b =>
                {
                    b.Property<int>("SubjectLecturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectLecturerId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("SubjectLecturerId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectId", "LecturerId")
                        .IsUnique();

                    b.ToTable("SubjectLecturers");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.UserSubscription", b =>
                {
                    b.Property<int>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSubscriptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Chapter", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatMessage", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatMessageSource", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatMessage", "ChatMessage")
                        .WithMany("Sources")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.DocumentChunk", "DocumentChunk")
                        .WithMany()
                        .HasForeignKey("DocumentChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatMessage");

                    b.Navigation("DocumentChunk");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatSession", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChunkingConfiguration", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Document", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Reviewer");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.DocumentChunk", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Payment", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Package", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.UserSubscription", "SourceSubscription")
                        .WithMany()
                        .HasForeignKey("SourceSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("SourceSubscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchDocumentChunk", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchQuestion", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Document", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId");

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("SourceDocument");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchResult", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchExperiment", "ResearchExperiment")
                        .WithMany("Results")
                        .HasForeignKey("ResearchExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchQuestion", "ResearchQuestion")
                        .WithMany("Results")
                        .HasForeignKey("ResearchQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResearchExperiment");

                    b.Navigation("ResearchQuestion");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.SubjectLecturer", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Subject", "Subject")
                        .WithMany("SubjectLecturers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.UserSubscription", b =>
                {
                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.Package", "Package")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Chapter", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatMessage", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Package", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchExperiment", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.ResearchQuestion", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Documents");

                    b.Navigation("SubjectLecturers");
                });

            modelBuilder.Entity("PRN212_VietnameseEduChat.BusinessObjects.Entities.User", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
